name: Build Geode Mod

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android
          os: ubuntu-latest
          platform: Android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        sdk: v2.0.0-beta.27
        platform: ${{ matrix.config.target }}
